// automatically generated by the FlatBuffers compiler, do not modify

package org.binave.common.serialize.flatbuffers;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Struct;

import java.nio.*;
import java.lang.*;

@SuppressWarnings("unused")
public final class Child extends Struct {
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Child __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long id() { return bb.getLong(bb_pos + 0); }
  public byte name() { return bb.get(bb_pos + 8); }

  public static int createChild(FlatBufferBuilder builder, long id, byte name) {
    builder.prep(8, 16);
    builder.pad(7);
    builder.putByte(name);
    builder.putLong(id);
    return builder.offset();
  }
}

