// automatically generated by the FlatBuffers compiler, do not modify

package org.binave.common.serialize.flatbuffers;

import java.nio.*;
import java.lang.*;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

/*
namespace org.binave.common.serialize.flatbuffers;

struct Child {
    id:long;
    name:byte;
}

table Person {
    id : long;
    name : string;
    friends : [Person];
}

root_type Person;
 */
@SuppressWarnings("unused")
public final class PersonData extends Table {
    public static PersonData getRootAsPerson(ByteBuffer _bb) {
        return getRootAsPerson(_bb, new PersonData());
    }

    public static PersonData getRootAsPerson(ByteBuffer _bb, PersonData obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public void __init(int _i, ByteBuffer _bb) {
        bb_pos = _i;
        bb = _bb;
    }

    public PersonData __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public long id() {
        int o = __offset(4);
        return o != 0 ? bb.getLong(o + bb_pos) : 0L;
    }

    public String name() {
        int o = __offset(6);
        return o != 0 ? __string(o + bb_pos) : null;
    }

    public ByteBuffer nameAsByteBuffer() {
        return __vector_as_bytebuffer(6, 1);
    }

    public PersonData friends(int j) {
        return friends(new PersonData(), j);
    }

    public PersonData friends(PersonData obj, int j) {
        int o = __offset(8);
        return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null;
    }

    public int friendsLength() {
        int o = __offset(8);
        return o != 0 ? __vector_len(o) : 0;
    }

    public static int createPerson(FlatBufferBuilder builder,
                                   long id,
                                   int nameOffset,
                                   int friendsOffset) {
        builder.startObject(3);
        PersonData.addId(builder, id);
        PersonData.addFriends(builder, friendsOffset);
        PersonData.addName(builder, nameOffset);
        return PersonData.endPerson(builder);
    }

    public static void startPerson(FlatBufferBuilder builder) {
        builder.startObject(3);
    }

    public static void addId(FlatBufferBuilder builder, long id) {
        builder.addLong(0, id, 0L);
    }

    public static void addName(FlatBufferBuilder builder, int nameOffset) {
        builder.addOffset(1, nameOffset, 0);
    }

    public static void addFriends(FlatBufferBuilder builder, int friendsOffset) {
        builder.addOffset(2, friendsOffset, 0);
    }

    public static int createFriendsVector(FlatBufferBuilder builder, int[] data) {
        builder.startVector(4, data.length, 4);
        for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]);
        return builder.endVector();
    }

    public static void startFriendsVector(FlatBufferBuilder builder, int numElems) {
        builder.startVector(4, numElems, 4);
    }

    public static int endPerson(FlatBufferBuilder builder) {
        int o = builder.endObject();
        return o;
    }

    public static void finishPersonBuffer(FlatBufferBuilder builder, int offset) {
        builder.finish(offset);
    }
}

